##
## wdnet: Weighted directed network
## Copyright (C) 2022  Yelie Yuan, Tiandong Wang, Jun Yan and Panpan Zhang
## Yelie Yuan <yelie.yuan@uconn.edu>
##
## This file is part of the R package wdnet.
##
## The R package wdnet is free software: You can redistribute it and/or
## modify it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or any later
## version (at your option). See the GNU General Public License at
## <https://www.gnu.org/licenses/> for details.
##
## The R package wdnet is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    invisible(.Call(`_wdnet_hello_world`))
}

fx <- function(x, Y, z) {
    .Call(`_wdnet_fx`, x, Y, z)
}

#' Degree preserving rewiring process for directed networks.
#'
#' @param iteration Integer, number of iterations for nattemtps rewiring attempts.
#' @param nattempts Integer, number of rewiring attempts per iteration.
#' @param targetNode Vector, target node sequence - 1.
#' @param sourceOut Vector, sequence of source nodes' out-degree.
#' @param sourceIn Vector, sequence of ource nodes' in-degree.
#' @param targetOut Vector, sequence of target nodes' out-degree.
#' @param targetIn Vector, sequence of target nodes' in-degree.
#' @param r_sourceOut Vector, sequence of rank of source nodes' out-degree.
#' @param r_sourceIn Vector, sequence of rank of source nodes' in-degree.
#' @param r_targetOut Vector, sequence of rank of target nodes' out-degree.
#' @param r_targetIn Vector, sequence of rank of target nodes' in-degree.
#' @param index_s Index sequence of source nodes' out- and in-degree. 
#'   index_s/index_t bridges the indices of source/target nodes and the 
#'   target structure eta.
#' @param index_t Index sequence of target nodes' out- and in-degree. 
#' @param eta Matrix, target structure eta generated by
#'   \code{wdnet::joint_dist_directed()}.
#' @param rewire_track Logical, whether the rewiring history should be returned.
#' @return Target node sequence, four directed assortativity coefficients after
#'   each iteration, result of rewiring attempts, edge scenarios of accepted rewiring 
#'   attempts, and percentage of accepted rewiring attempts.
#'
rewire_directed_cpp <- function(iteration, nattempts, targetNode, sourceOut, sourceIn, targetOut, targetIn, r_sourceOut, r_sourceIn, r_targetOut, r_targetIn, index_s, index_t, eta, rewire_track) {
    .Call(`_wdnet_rewire_directed_cpp`, iteration, nattempts, targetNode, sourceOut, sourceIn, targetOut, targetIn, r_sourceOut, r_sourceIn, r_targetOut, r_targetIn, index_s, index_t, eta, rewire_track)
}

#' Degree preserving rewiring process for undirected networks.
#' 
#' @param iteration Integer, number of iterations for nattemtps rewiring attempts.
#' @param nattempts Integer, number of rewiring attempts for each iteration.
#' @param node1 Vector, node sequence of the first column of edgelist.
#' @param node2 Vector, node sequence of the second column of edgelist.
#' @param degree1 Vector, degree sequence of node1 and node2.
#' @param degree2 Vector, degree sequence of node2 and node1. degree1 
#'   and degree2 are used to calculate assortativity coefficient,
#'   i.e., degree correlation.
#' @param index1 Index sequence of the first column of edgelist. 
#'   index1 and index2 bridge the nodes' degree and the 
#'   structure e.
#' @param index2 Index sequence of the second column of edgelist..
#' @param e Matrix, target structure e generated by
#'   \code{wdnet::joint_dist_undirected()}.
#' @param rewire_track Logical, whether the rewiring history should be returned.
#' @return Node sequences, node indexes and rewiring history.
#'
rewire_undirected_cpp <- function(iteration, nattempts, node1, node2, degree1, degree2, index1, index2, e, rewire_track) {
    .Call(`_wdnet_rewire_undirected_cpp`, iteration, nattempts, node1, node2, degree1, degree2, index1, index2, e, rewire_track)
}

#' Fill missing values in node sequence.
#'
#' @param nodes Sequence of source/target node of edges, missing values are denoted as 0.
#' @param edges Sampled edges according to preferential attachment.
#' @return Sequence of source/target node of edges.
findNode_cpp <- function(nodes, edges) {
    .Call(`_wdnet_findNode_cpp`, nodes, edges)
}

#' Fill missing values in node sequence.
#'
#' @param start_node Sequence of nodes from the first column of edgelist, i.e., \code{edgelist[, 1]}.
#' @param end_node Sequence of nodes from the first column of edgelist, i.e., \code{edgelist[, 2]}.
#' @param start_edge Index of sampled edges, corresponds to the missing nodes in start_node.
#' @param end_edge Index of sampled edges, corresponds to the missing nodes in end_node.
#' @return Sequence of source/target node of edges.
findNode_undirected_cpp <- function(start_node, end_node, start_edge, end_edge) {
    .Call(`_wdnet_findNode_undirected_cpp`, start_node, end_node, start_edge, end_edge)
}

#' Aggregate edgeweight into nodes' strength.
#'
#' @param start_node Sequence of source nodes.
#' @param end_node Sequence of target nodes.
#' @param weight Sequence of edgeweight.
#' @param nnode Number of nodes of sampled network.
#' @param weighted Logical, ture if the edges are weighted, 
#'   false if not.
#' @return Sequence of outstrength/instrength.
nodeStrength_cpp <- function(start_node, end_node, weight, nnode, weighted = TRUE) {
    .Call(`_wdnet_nodeStrength_cpp`, start_node, end_node, weight, nnode, weighted)
}

#' Sample nodes with respect to the number of nodes at each step.
#'
#' @param total_node Number of nodes at each step.
#' @return Sequence of sampled nodes.
sampleNode_cpp <- function(total_node) {
    .Call(`_wdnet_sampleNode_cpp`, total_node)
}

#' Preferential attachment algorithm for simple situations, 
#' e.g., edge weights are constant, 
#' number of new edges per step is 1.
#'
#' @param start_node Sequence of source nodes.
#' @param end_node Sequence of target nodes.
#' @param scenario Sequence of alpha, beta, gamma, xi, rho scenarios.
#' @param nnode Number of nodes at current step.
#' @param nedge Number of edges at current step.
#' @param delta_out Tuning parameter.
#' @param delta_in Tuning parameter.
#' @param directed Whether the network is directed.
#' @return Number of nodes, sequences of source and target nodes.
#' 
rpanet_cpp <- function(start_node, end_node, scenario, nnode, nedge, delta_out, delta_in, directed) {
    .Call(`_wdnet_rpanet_cpp`, start_node, end_node, scenario, nnode, nedge, delta_out, delta_in, directed)
}

