##
## wdnet: Weighted directed network
## Copyright (C) 2021  Yelie Yuan, Panpan Zhang, and Jun Yan
## Jun Yan <jun.yan@uconn.edu>
##
## This file is part of the R package wdnet.
##
## The R package wdnet is free software: You can redistribute it and/or
## modify it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or any later
## version (at your option). See the GNU General Public License at
## <https://www.gnu.org/licenses/> for details.
##
## The R package wdnet is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    invisible(.Call(`_wdnet_hello_world`))
}

fx <- function(x, Y, z) {
    .Call(`_wdnet_fx`, x, Y, z)
}

#' Degree preserving rewiring process for directed networks.
#'
#' @param iteration Integer, number of iterations for nattemtps rewiring attempts.
#' @param nattempts Integer, number of rewiring attempts per iteration.
#' @param targetNode Vector, target node sequence - 1.
#' @param sourceOut Vector, sequence of source nodes' out-degree.
#' @param sourceIn Vector, sequence of ource nodes' in-degree.
#' @param targetOut Vector, sequence of target nodes' out-degree.
#' @param targetIn Vector, sequence of target nodes' in-degree.
#' @param r_sourceOut Vector, sequence of rank of source nodes' out-degree.
#' @param r_sourceIn Vector, sequence of rank of source nodes' in-degree.
#' @param r_targetOut Vector, sequence of rank of target nodes' out-degree.
#' @param r_targetIn Vector, sequence of rank of target nodes' in-degree.
#' @param index_s Index sequence of source nodes' out- and in-degree. 
#'   index_s/index_t bridges the indices of source/target nodes and the 
#'   target structure eta.
#' @param index_t Index sequence of target nodes' out- and in-degree. 
#' @param eta Matrix, target structure eta generated by
#'   wdnet::directed_joint_dist().
#' @param rewireTrack Logical, whether the rewiring history should be returned.
#' @return Target node sequence, four directed assortativity coefficients after
#'   each iteration, result of rewiring attempts, edge scenarios of accepted rewiring 
#'   attempts, and percentage of accepted rewiring attempts.
#'
directed_rewire_cpp <- function(iteration, nattempts, targetNode, sourceOut, sourceIn, targetOut, targetIn, r_sourceOut, r_sourceIn, r_targetOut, r_targetIn, index_s, index_t, eta, rewireTrack) {
    .Call(`_wdnet_directed_rewire_cpp`, iteration, nattempts, targetNode, sourceOut, sourceIn, targetOut, targetIn, r_sourceOut, r_sourceIn, r_targetOut, r_targetIn, index_s, index_t, eta, rewireTrack)
}

#' Degree preserving rewiring process for undirected networks.
#' 
#' @param iteration Integer, number of iterations for nattemtps rewiring attempts.
#' @param nattempts Integer, number of rewiring attempts for each iteration.
#' @param node1 Vector, node sequence of the first column of edgelist.
#' @param node2 Vector, node sequence of the second column of edgelist.
#' @param degree1 Vector, degree sequence of node1 and node2.
#' @param degree2 Vector, degree sequence of node2 and node1. degree1 
#'   and degree2 are used to calculate assortativity coefficient,
#'   i.e., degree correlation.
#' @param index1 Index sequence of the first column of edgelist. 
#'   index1 and index2 bridge the nodes' degree and the 
#'   structure e.
#' @param index2 Index sequence of the second column of edgelist..
#' @param e Matrix, target structure e generated by
#'   wdnet::undirected_joint_dist().
#' @param rewireTrack Logical, whether the rewiring history should be returned.
#' @return Node sequences, node indexes and rewiring history.
#'
undirected_rewire_cpp <- function(iteration, nattempts, node1, node2, degree1, degree2, index1, index2, e, rewireTrack) {
    .Call(`_wdnet_undirected_rewire_cpp`, iteration, nattempts, node1, node2, degree1, degree2, index1, index2, e, rewireTrack)
}

#' Fill missing values in node sequence.
#'
#' @param nodes Sequence of source/target node of edges, missing values are denoted as 0.
#' @param edges Edges sampled according to preferential attachment.
#' @param index Index of missing values in nodes.
#' @return Sequence of source/target node of edges.
findNode_cpp <- function(nodes, edges, index) {
    .Call(`_wdnet_findNode_cpp`, nodes, edges, index)
}

#' Aggregate edgeweight into nodes' strength.
#'
#' @param startNode Sequence of source nodes.
#' @param endNode Sequence of target nodes.
#' @param weight Sequence of edgeweight.
#' @param nNodes Number of nodes of sampled network.
#' @param weighted Logical, ture if the edges are weighted, 
#'   false if not.
#' @return Sequence of outstrength/instrength.
nodeStrength_cpp <- function(startNode, endNode, weight, nNodes, weighted = TRUE) {
    .Call(`_wdnet_nodeStrength_cpp`, startNode, endNode, weight, nNodes, weighted)
}

#' Sample nodes with respect to the number of nodes at each step.
#'
#' @param totalNode Number of nodes at each step.
#' @return Sequence of sampled nodes.
sampleNode_cpp <- function(totalNode) {
    .Call(`_wdnet_sampleNode_cpp`, totalNode)
}

#' Preferential attachment algorithm for simple situations, 
#' e.g., edge weights are constant, 
#' number of new edges per step is 1.
#'
#' @param startNode Sequence of source nodes.
#' @param endNode Sequence of target nodes.
#' @param scenario Sequence of alpha, beta, gamma, xi, rho scenarios.
#' @param nNodes Number of nodes at current step.
#' @param nEdges Number of edges at current step.
#' @param delta_out Tuning parameter.
#' @param delta_in Tuning parameter.
#' @return Number of nodes, sequences of source and target nodes.
#' 
rpanet_cpp <- function(startNode, endNode, scenario, nNodes, nEdges, delta_out, delta_in) {
    .Call(`_wdnet_rpanet_cpp`, startNode, endNode, scenario, nNodes, nEdges, delta_out, delta_in)
}

#' Sample a node according to node strength.
#'
#' @param tnode Number of nodes at current step.
#' @param sumstrength Total strength at current step.
#' @param strength Vector of node strength.
#' @param delta The tuning parameter, delta_in or delta_out.
#' @return Sampled node.
sampleNode_simple_cpp <- function(tnode, sumstrength, strength, delta) {
    .Call(`_wdnet_sampleNode_simple_cpp`, tnode, sumstrength, strength, delta)
}

#' Sample a node according to node strength.
#'
#' @param nsteps Number of steps.
#' @param control Vector of control parameters, i.e., alpha, beta,
#'   gamma, xi, delta_in and delta_out.
#' @param m Vector, number of edges at each step.
#' @param w Weight of new edges.
#' @param outstrength Vector of node out-strength.
#' @param instrength Vector of node in-strength.
#' @param sumstrength Total strength of inital network.
#' @param nnode Number of nodes of inital network.
#' @return A list of source nodes, target nodes, node out- and in-strength.
rpanet_simple_cpp <- function(nsteps, control, m, w, outstrength, instrength, sumstrength, nnode) {
    .Call(`_wdnet_rpanet_simple_cpp`, nsteps, control, m, w, outstrength, instrength, sumstrength, nnode)
}

